version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  elixir_app_1:
    build: .
    environment:
      - REDIS_HOST=redis
      - NODE_NAME=app1
    links:
      - redis
    depends_on:
      - redis

  elixir_app_2:
    build: .
    environment:
      - REDIS_HOST=redis
      - NODE_NAME=app2
    links:
      - redis
    depends_on:
      - redis
